//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluffMonsters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public Pet()
        {
            this.Owners = new HashSet<Customer>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Breed { get; set; }
        public string Species { get; set; }
        public string FavoriteToy { get; set; }
        public double WeightInKilograms { get; set; }
        public double HeightInMeters { get; set; }
        public string Notes { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<Customer> Owners { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
